---
name: Qualify Code (reusable)

"on":
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-common-uv-qualify:
    # このプロジェクトは pyproject.toml で requires-python = ">=3.13,<3.14" を要求するため 3.13 のみ
    uses: Seika139/.github/.github/workflows/uv-qualify.yml@main
    with:
      python-version: "3.13"
    secrets: inherit
